name: nfc_pro_manager
description: The industry-grade NFC SDK for Flutter. Supports robust Host Card Emulation (HCE), Identity Emulation, NDEF Read/Write, and ISO-DEP APDU communication with enterprise lifecycle management.
version: 2.3.0
homepage: https://github.com/Royhan2123/NFC-MANAGER
repository: https://github.com/Royhan2123/NFC-MANAGER
issue_tracker: https://github.com/Royhan2123/NFC-MANAGER/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.kotlin_nfc_manager
        pluginClass: NfcProPlugin
      ios:
        pluginClass: NfcProPlugin
